apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-new-backend
spec:
  selector:
    matchLabels:
      app: spring-boot
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        image: ervisa/backend-new:1
        ports:
        - containerPort: 8080
